### ISSUE TITLE
Orphaned attachments (images) are visible in 'Nuke orphaned files' but not visible in 'Nuke orphaned attachments. Why?

### ISSUE THREAD

**Issue by VKondakoff** [sandorex/nuke-orphans#11]
Hi!

Just noticed: some attachments (images) are visible in `Nuke orphaned files` but not visible in `Nuke orphaned attachments`. Why this happens?

`Nuke orphaned files:`

<img width="863" alt="Снимок экрана 2024-03-20 в 14 57 11" src="https://github.com/sandorex/nuke-orphans-plugin/assets/230824/db11ff43-480f-4a18-a26e-ecbbc7e7234a">

`Nuke orphaned attachments:`

<img width="508" alt="Снимок экрана 2024-03-20 в 14 58 02" src="https://github.com/sandorex/nuke-orphans-plugin/assets/230824/a704da26-fa7c-4845-b067-af1b29174003">

MacOS, NO 1.2.5, Obsidian 1.5.11

**Comment by sandorex** [comment]
Could you provide a minimal vault that i could use to debug this?

**Comment by VKondakoff** [comment]
No need for this: I have found a reason of this behaviour. Here is my Obsidian Files and Links config:

<img width="1094" alt="Снимок экрана 2024-03-20 в 18 23 52" src="https://github.com/sandorex/nuke-orphans-plugin/assets/230824/0a5ac729-ebd6-4d46-b052-f83c93c101ad">

Attachment folder path is set to `assets`, while actual folder was named `Assets`. This does not prevents Obsidian to work as expected, but breaks NO `Nuke orphaned links` command. If I change the attachment folder name in Obsidian config to `Assets` - NO starts to work as exected. If I change it back to `assets` - NO could not find the orphaned attachments.

So - this is a case sensitivity issue.

**Comment by sandorex** [comment]
This is intended behavior of the plugin, but it is weird that obsidian is case insensitive

The reason for difference between 'Nuke Orphaned Files' and 'Nuke Orphaned Attachments' is cause of different APIs used, first reading the files using the attachment path, latter reading only obsidian cached data
