### ISSUE TITLE
Attachments in Codeblock will not be considered in use

### ISSUE THREAD

**Issue by Moyf** [sandorex/nuke-orphans#12]
![image](https://github.com/sandorex/nuke-orphans-plugin/assets/4013062/1dc1aad3-7621-42c6-bf3f-81466d21eab4)
If I put a image in admonition block, it would not be considered in use, and will be deleted when using the "Trash orphaned attachments" command.

I guess it might due to the Code Block (which doesn't actually compile the content in it? ) 🤔
Could this be fixed? Or is this a flaw in Obsidian itself?

**Comment by sandorex** [comment]
This is a feature specific to that plugin, only attachments added by builtin obsidian features can be found through the API

Only partial solution i see is to ignore a custom path where you'll store the attachments for that plugin, that way at least they wont be deleted
