### ISSUE TITLE
Feature Request: Ignore Patterns able to be set for any search type

### ISSUE THREAD

**Issue by technotherion** [sandorex/nuke-orphans#13]
I have folder notes with the extension .README that are often blank, but I do not want to delete them when deleting empty files. 

Under Ignore Patterns I've added ".readme" and ".README" and this works great... but only when I'm using "Find Orphaned Files". 

Maybe there could be different checkboxes for what the ignore patterns apply to. One checkbox could be "when searching for orphans" and another could be "when searching for empty files" or "when searching for untagged files" etc.

**Comment by sandorex** [comment]
Ill look into it, could be useful but can't give any ETA

**Comment by technotherion** [comment]
The new update works perfectly for my needs. Thank you!

**Comment by sandorex** [comment]
But i didn't do anything yet?

Glad it's working now though :)
